- platform: mqtt
  name: "Shop Outside East"
  command_topic: "cmnd/dimmer1/POWER"
  state_topic: "tele/dimmer1/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/dimmer1/LWT"
  brightness_command_topic: "cmnd/dimmer1/Dimmer"
  brightness_state_topic: "tele/dimmer1/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

  
- platform: mqtt
  name: "Yardlight"
  command_topic: "cmnd/dimmer2/POWER"
  state_topic: "tele/dimmer2/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/dimmer2/LWT"
  brightness_command_topic: "cmnd/dimmer2/Dimmer"
  brightness_state_topic: "tele/dimmer2/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "RGB Light 1"
  command_topic: "cmnd/feitLight1/POWER"
  state_topic: "tele/feitLight1/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/feitLight1/LWT"
  brightness_command_topic: "cmnd/feitLight1/Dimmer"
  brightness_state_topic: "tele/feitLight1/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/feitLight1/CT"
  color_temp_state_topic: "tele/feitLight1/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/feitLight1/Color2"
  rgb_state_topic: "tele/feitLight1/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/feitLight1/Scheme"
  effect_state_topic: "tele/feitLight1/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

- platform: mqtt
  name: "RGB Light 2"
  command_topic: "cmnd/feitLight2/POWER"
  state_topic: "tele/feitLight2/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/feitLight2/LWT"
  brightness_command_topic: "cmnd/feitLight2/Dimmer"
  brightness_state_topic: "tele/feitLight2/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/feitLight2/CT"
  color_temp_state_topic: "tele/feitLight2/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/feitLight2/Color2"
  rgb_state_topic: "tele/feitLight2/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/feitLight2/Scheme"
  effect_state_topic: "tele/feitLight2/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
