title: Home
views:
  - path: default_view
    title: Main
    badges: []
    cards:
      - type: entities
        entities:
          - sensor.downstairs_thermostat_temperature
          - sensor.outside_temp
        title: Weather
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.fridge_temp
          - sensor.fridge_humid
          - sensor.freezer_temp
          - sensor.deep_freeze
        title: Fridge and Freezers 
        show_header_toggle: false

      - type: history-graph
        entities:
          - sensor.filtered_fridge_temp
          - sensor.freezer_temp
          - sensor.deep_freeze
        title: Fridge History 

      - type: history-graph
        entities:
          - sensor.14789t 
          - sensor.14789h 
          - sensor.12391t 
          - sensor.12391h 
          - sensor.6312t 
          - sensor.6312h 
          - sensor.6692t 
          - sensor.6692h 
        title: Temperatures 


      - type: history-graph
        entities:
          - sensor.total_steps
          - sensor.daily_step_goal
        title: Garmin Steps

      - type: history-graph
        entities:
          - sensor.floors_ascended_goal
          - sensor.floors_ascended
          - sensor.floors_descended  
        title: Garmin Steps
        
      - type: history-graph
        entities:
          - sensor.max_stress_level
          - sensor.medium_stress_duration
          - sensor.rest_stress_duration
          - sensor.activity_stress_duration
          - sensor.avg_stress_level
          - sensor.high_stress_duration
          - sensor.low_stress_duration
          - sensor.total_stress_duration
          - sensor.uncat_stress_duration
        title: Garmin Stress

      - type: history-graph
        entities:
          - sensor.resting_heart_rate
          - sensor.max_heart_rate
          - sensor.min_heart_rate  
        title: Garmin Heart

      - type: entities
        entities:
          - sensor.14789t 
          - sensor.14789h 
          - sensor.12391t 
          - sensor.12391h 
          - sensor.6312t 
          - sensor.6312h 
          - sensor.6692t 
          - sensor.6692h 
        title: Temperatures 
      - type: entities
        entities:
          - light.yardlight
          - light.porch_light
          - light.cree_connected_a_19_60w_equivalent_fe067982_10
          - light.cree_connected_a_19_60w_equivalent_fe04b14c_10
          - light.rgb_light_1  
          - light.rgb_light_2  
          - light.upstairs_bedroom
          - light.office_dimmer
          - lock.front_door 
          - lock.garage_door
          - lock.shop_door
          - lock.laundry_door
  
        title: Lights
        show_header_toggle: true
      - type: alarm-panel
        entity: alarm_control_panel.home_alarm
      - type: alarm-panel
        entity: alarm_control_panel.shop_alarm
      - type: entities
        entities:
          - sensor.hot_water_temp_out
          - switch.hotwater
        title: Water Temperature
        show_header_toggle: true
      - type: entities
        entities:
          - switch.skylight
          - switch.skylight_fan
          - input_number.fan_run_time
        title: Fan
        show_header_toggle: true
      - type: entities
        entities:
          - input_number.dsbathfan_run_time
          - switch.ds_bath_fan
          - input_number.usbathfan_run_time
          - switch.us_bath_fan
        title: Bathroom Fans
        show_header_toggle: true
      - type: picture-entity
        entity: camera.weather_camera_1
      - type: picture-entity
        entity: camera.camera_1
        #- type: picture-entity
        #entity: camera.camera_2
  - path: alarms
    title: Alarms
    badges: []
    cards:
      - type: entities
        entities:
          - switch.garage_outside
          - light.shop_outside_east   
          - light.sengled_e11_g13_03074c6b_1
          - light.sengled_e11_g13_03076ad2_1
          - light.sengled_e11_g13_03077131_1
          - light.sengled_e11_g13_030781cc_1
          - light.landscape_lights 
        title: Outside Lights
        show_header_toggle: true
      - type: entities
        entities:
          - sensor.shop_alarm_keypad
          - binary_sensor.shop_door_east
          - binary_sensor.shop_overhead
          - binary_sensor.shop_door_south
          - binary_sensor.shop_windows
          - binary_sensor.shop_smoke
          - binary_sensor.shop_heat
        title: Shop Alarm
        show_header_toggle: true
      - type: alarm-panel
        entity: alarm_control_panel.shop_alarm
      - type: entities
        entities:
          - sensor.home_alarm_keypad
          - binary_sensor.front_door
          - binary_sensor.east_door
          - binary_sensor.first_floor_motion
          - binary_sensor.north_double_door
          - binary_sensor.laundry_room
          - binary_sensor.bathroom
        title: Home Alarm
        show_header_toggle: true
      - type: alarm-panel
        entity: alarm_control_panel.home_alarm
      - type: entities
        entities:
          - switch.coop_door
          - switch.relay_1
          - switch.relay_2
          - switch.relay_3
          - switch.relay_4
          - switch.relay_5
          - switch.relay_6
          - switch.relay_7
          - switch.relay_8
          - switch.shop_center  
          - switch.shop_north  
          - switch.shop_south
          - sensor.centralite_3210_l_cc10a60c_electrical_measurement
          - switch.centralite_3210_l_cc10a60c_on_off
          - sensor.centralite_3210_l_cc10a60c_smartenergy_metering  
        title: Garden
        show_header_toggle: true
  - path: device_tracker
    title: Device Tracker
    badges: []
    cards: []
  - path: automation
    title: Automations
    badges: []
    cards: []
  - path: indoorclimate
    title: Indoor Climate
    badges: []
    cards:
      - type: entities
        entities:
          - binary_sensor.downstairs_thermostat_fan
          - binary_sensor.downstairs_thermostat_has_leaf
          - binary_sensor.downstairs_thermostat_is_locked
          - binary_sensor.downstairs_thermostat_is_using_emergency_heat
          - binary_sensor.downstairs_thermostat_online
          - sensor.downstairs_thermostat_humidity
          - sensor.downstairs_thermostat_hvac_state
          - sensor.downstairs_thermostat_operation_mode
          - sensor.downstairs_thermostat_target
          - sensor.downstairs_thermostat_temperature
        title: Nest
        show_header_toggle: true
      - type: entities
        entities:
          - sensor.hot_water_temp_in
          - sensor.hot_water_temp_out
          - sensor.cold_water_temp_in
          - sensor.master_shower_temp
        title: Water
        show_header_toggle: true
      - type: entities
        entities:
          - water_heater.waterheater
        title: WaterHeater
        show_header_toggle: true
      - type: entities
        entities:
          - sensor.front_door_lock_status
          - sensor.lock_front_door_battery
          - sensor.garage_door_lock_status
          - sensor.lock_garage_door_battery
          - sensor.shop_door_lock_status
          - sensor.lock_shop_door_battery
          - sensor.laundry_door_lock_status
          - sensor.lock_laundry_door_battery
        title: Lock Status
        show_header_toggle: false
      - type: entities
        entities:
          - sensor.ups_name
          - sensor.ups_load
          - sensor.ups_time_left
          - sensor.ups_input_voltage
          - sensor.ups_transfer_high
          - sensor.ups_transfer_low
          - sensor.ups_last_transfer
          - sensor.ups_transfer_from_battery
        title: UPS
        show_header_toggle: true
  - path: environment
    title: Environment
    badges: []
    cards:
      - type: entities
        entities:
          - sensor.aq_temperature_1
          - sensor.aq_pressure_1
          - sensor.aq_quality_1
          - sensor.aq_temperature_2
          - sensor.aq_pressure_2
          - sensor.aq_humidity_2
          - sensor.battery_current
          - sensor.battery_voltage
          - sensor.battery_power
          - sensor.nest_box_1
          - sensor.nest_box_2
          - sensor.nest_box_3
          - sensor.nest_box_4
        title: Environmental
        show_header_toggle: true
      - type: entities
        entities:
          - sensor.solaredge_current_power_template
          - sensor.solaredge_last_day_data_template
          - sensor.solaredge_last_month_data_template
          - sensor.solaredge_last_year_data_template
        title: Solar
        show_header_toggle: true
      - type: entities
        entities:
          - binary_sensor.ender_3_pro_printing
          - binary_sensor.ender_3_pro_printing_error
          - sensor.ender_3_pro_current_state
          - sensor.ender_3_pro_job_percentage
          - switch.printer_power
        title: Ender
        show_header_toggle: true
      - type: picture-entity
        entity: camera.octoprint
      - type: entities
        entities:
          - switch.pool_pump
          - switch.pool_cleaner
          - switch.chlorine_generator
          - switch.pool_drain
          - sensor.pool_pressure
          - sensor.cleaner_pressure
        title: pool
        show_header_toggle: false

